Repository ansible/ansible-compat, pull requests merged in 2022-11, with the labels that each got.

#170 Enable testing with ansible 2.14
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog

#180 Avoid running galaxy on offline mode
  .pre-commit-config.yaml
  src/ansible_compat/runtime.py
  test/test_runtime.py
Labels: bug

#181 Bump test deps
  docs/conf.py
  requirements.txt
  setup.cfg
Labels: skip-changelog

#185 Update devtools repo url
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
  README.md
  setup.cfg
Labels: bug, skip-changelog

#186 Update build-system dependency for setuptools-scm to >= 7.0.0
  pyproject.toml
Labels: bug

#188 Log current directory before running galaxy install
  src/ansible_compat/runtime.py
Labels: bug

#189 Make twine check strict
  tox.ini
Labels: skip-changelog

#190 Make galaxy installation verbose
  src/ansible_compat/runtime.py
Labels: bug

#192 Revert "Avoid running galaxy on offline mode (#180)"
  .pre-commit-config.yaml
  src/ansible_compat/runtime.py
  test/test_runtime.py
Labels: bug

#193 Upgrade tox config
  .github/workflows/tox.yml
  pyproject.toml
  tox.ini
Labels: skip-changelog

#195 Adopt PEP-621 for packaging
  .pre-commit-config.yaml
  pyproject.toml
  requirements.txt
  setup.cfg
  src/ansible_compat/__init__.py
  tox.ini
Labels: enhancement

#196 More GHA fixes
  .github/workflows/release.yml
  .github/workflows/tox.yml
Labels: skip-changelog
