Repository ansible/ansible-compat, pull requests merged in 2023-01, with the labels that each got.

#211 Required subprocess-tee>=0.4.1
  .pre-commit-config.yaml
  pyproject.toml
  requirements.txt
Labels: bug

#208 Use dynamic matrix
  .github/workflows/tox.yml
Labels: skip-changelog

#212 Switch from sphinx to mkdocs
  docs/api.md
  docs/conf.py
  docs/examples.md
  docs/images/favicon.ico
  docs/images/logo.png
  docs/images/logo.svg
  docs/index.md
  mkdocs.yml
  pyproject.toml
  readthedocs.yml
  requirements.txt
  src/ansible_compat/config.py
  src/ansible_compat/runtime.py
  tox.ini
Labels: skip-changelog

#214 Update linters
  .pre-commit-config.yaml
Labels: skip-changelog

#215 Require ansible-core 2.12 or newer
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  pyproject.toml
  requirements.txt
  src/ansible_compat/config.py
  src/ansible_compat/constants.py
  src/ansible_compat/runtime.py
  test/test_config.py
  tox.ini
Labels: major

#213 Address ansible 2.15 compatibility related to AnsibleCollectionConfig
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  pyproject.toml
  src/ansible_compat/runtime.py
  test/test_runtime.py
  tox.ini
Labels: enhancement
