Repository ansible/ansible-compat, pull requests merged in 2023-05, with the labels that each got.

#256 Rename Runtime.exec to Runtime.run
  pyproject.toml
  src/ansible_compat/runtime.py
  test/test_runtime.py
  test/test_runtime_example.py
Labels: major

#261 Revert to previous behavior for ansible_collections_path
  src/ansible_compat/config.py
Labels: bug

#264 Include original message in AnsibleWarning
  .pre-commit-config.yaml
  src/ansible_compat/runtime.py
Labels: bug

#263 Remove pypi need for credentials
  .github/workflows/release.yml
Labels: skip-changelog

#265 Also install requirements from galaxy.yml files
  .pre-commit-config.yaml
  .vscode/settings.json
  pyproject.toml
  src/ansible_compat/constants.py
  src/ansible_compat/runtime.py
  test/collections/acme.goodies/galaxy.yml
  test/test_runtime.py
Labels: bug

#266 Automatically install tests/requirements.yml when found
  src/ansible_compat/runtime.py
  test/collections/acme.goodies/tests/requirements.yml
  test/test_runtime.py
Labels: bug

#268 Allow use of * version on dependencies
  src/ansible_compat/runtime.py
  test/collections/acme.goodies/galaxy.yml
  test/test_runtime.py
Labels: bug

#272 Update test dependencies and enable ansible 2.15 testing
  .github/workflows/tox.yml
  requirements.txt
  tox.ini
Labels: skip-changelog

#273 Correct coverage settings
  .gitignore
  pyproject.toml
  tox.ini
Labels: skip-changelog

#275 Improve requirements.yml detection
  examples/reqs_broken/requirements.yml
  src/ansible_compat/constants.py
  src/ansible_compat/runtime.py
  test/test_runtime.py
  tox.ini
Labels: bug

#277 Enable access to available plugins
  .gitignore
  .vscode/settings.json
  ansible.cfg
  pyproject.toml
  src/ansible_compat/runtime.py
  test/test_runtime.py
  tox.ini
Labels: enhancement

#282 Disable ruff autofixes in vscode
  .vscode/settings.json
Labels: skip-changelog

#283 Log retry attempt only when doing retries
  src/ansible_compat/runtime.py
Labels: bug

#284 Disable Ansible debug mode for sub-commands
  src/ansible_compat/runtime.py
Labels: bug
