Repository ansible/ansible-compat, pull requests merged in 2024-05, with the labels that each got.

#365 Update requirements
  .config/constraints.txt
  .config/requirements-docs.in
  .pre-commit-config.yaml
  .readthedocs.yml
  tox.ini
Labels: bug

#364 Add has_playbook method to Runtime
  src/ansible_compat/runtime.py
  test/test_runtime.py
  tox.ini
Labels: enhancement

#366 Upgrade gha upload-artifact
  .github/workflows/tox.yml
Labels: skip-changelog

#368 Remove before-release from GHA release pipeline
  .github/workflows/release.yml
Labels: skip-changelog

#374 Extend coverage
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  pyproject.toml
  src/ansible_compat/runtime.py
  test/roles/acme.missing_deps/requirements.yml
  test/test_config.py
  test/test_runtime.py
  test/test_schema.py
Labels: skip-changelog

#382 Removed leftover code related to ansible-core before 2.14
  .github/workflows/tox.yml
  src/ansible_compat/runtime.py
  test/test_runtime.py
Labels: bug

#378 Increase coverage
  .github/workflows/tox.yml
  .vscode/extensions.json
  .vscode/settings.json
  pyproject.toml
  src/ansible_compat/runtime.py
  test/test_types.py
  test/test_version.py
Labels: bug

#379 Correctly identify the installed collections when duplicates exist
  pyproject.toml
  src/ansible_compat/runtime.py
  test/test_runtime.py
Labels: bug

#383 Enable testing with released version on ansible 2.17
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog

#345 Fix packit configuration
  .config/python3-ansible-compat.spec
  .gitignore
  .packit.yaml
  tools/get-version.sh
  tools/update-version.sh
  tox.ini
Labels: skip-changelog

#315 Test changelog on rpm
  .packit.yaml
  tools/update-spec.sh
  tools/update-version.sh
Labels: skip-changelog
