Repository ansible/ansible-compat, pull requests merged in 2024-12, with the labels that each got.

#429 Update prettier
  .config/constraints.txt
  .github/ISSUE_TEMPLATE/bug_report.md
  .pre-commit-config.yaml
Labels: skip-changelog, pre-commit

#428 Exclude pip check command for docs in tox.ini file
  tox.ini
Labels: skip-changelog, dependencies

#431 Use reusable tox workflow
  .config/constraints.txt
  .config/requirements-test.in
  .github/workflows/tox.yml
  .gitignore
  package-lock.json
  package.json
Labels: skip-changelog

#432 Use ubuntu 24.04 instead of 22.04 for testing
  .github/workflows/release.yml
  readthedocs.yml
Labels: skip-changelog
