Repository ansible/ansible-compat, pull requests merged in 2025-01, with the labels that each got.

#437 Refactor search_galaxy_paths to use pathlib
  .gitignore
  mkdocs.yml
  readthedocs.yml
  src/ansible_compat/runtime.py
  test/test_runtime.py
  tox.ini
Labels: bug

#441 Enable ruff preview rules and pydoclint
  .config/pydoclint-baseline.txt
  .pre-commit-config.yaml
  pyproject.toml
  src/ansible_compat/config.py
  src/ansible_compat/errors.py
  src/ansible_compat/runtime.py
  src/ansible_compat/schema.py
  src/ansible_compat/types.py
  test/conftest.py
  test/test_config.py
  test/test_runtime.py
  tox.ini
Labels: bug

#443 Support ansible 2.18, drop 2.14/2.15 and py39
  .config/requirements.in
  .github/workflows/tox.yml
  .readthedocs.yml
  README.md
  pyproject.toml
  src/ansible_compat/constants.py
  src/ansible_compat/runtime.py
  src/ansible_compat/types.py
  test/conftest.py
  test/test_config.py
  tox.ini
Labels: major

#444 Use correct init_plugin_loader
  src/ansible_compat/runtime.py
Labels: skip-changelog

#439 Change cache_dir location to prefer venv and project_directory
  .config/pydoclint-baseline.txt
  .taplo.toml
  .vscode/settings.json
  pyproject.toml
  src/ansible_compat/prerun.py
  src/ansible_compat/runtime.py
  test/test_prerun.py
  test/test_runtime.py
  test/test_runtime_scan_path.py
  tox.ini
Labels: bug

#446 Ensure we constrain test dependencies with uv
  tox.ini
Labels: skip-changelog

#449 Fail if old ANSIBLE_COLLECTIONS_PATHS is detected
  .config/pydoclint-baseline.txt
  .pre-commit-config.yaml
  src/ansible_compat/config.py
  src/ansible_compat/runtime.py
  test/test_config.py
  test/test_runtime.py
Labels: major

#450 Patch #449 to use ANSIBLE_COLLECTIONS_PATH
  src/ansible_compat/runtime.py
  test/test_runtime.py
Labels: bug

#447 Inject venv site-packages at the top of collection path (test isolation)
  .config/pydoclint-baseline.txt
  pyproject.toml
  src/ansible_compat/config.py
  src/ansible_compat/runtime.py
  test/test_runtime.py
  test/test_runtime_scan_path.py
  tools/smoke.py
  tox.ini
Labels: major

#453 Ensure that cache directory is writable
  src/ansible_compat/prerun.py
  test/test_prerun.py
Labels: skip-changelog

#456 Fix grammatical error in collection path info message
  src/ansible_compat/runtime.py
Labels: bug
