Repository ansible/ansible-compat, pull requests merged in 2025-04, with the labels that each got.

#478 Make warning signature compatible with ansible core 2.19
  .config/pydoclint-baseline.txt
  .pre-commit-config.yaml
  src/ansible_compat/runtime.py
Labels: bug

#479 Workaround for dependabot improper python version
  .python-version
  mise.toml
Labels: skip-changelog

#486 Enable junit.xml reporting to codecov.io
  .gitignore
  pyproject.toml
  tools/report-coverage
  tox.ini
Labels: patch
